name: Merge Schedule
on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize
  schedule:
    - cron: 0 9 * * *

jobs:
  merge_schedule:
    runs-on: ubuntu-latest
    steps:
      - uses: gr2m/merge-schedule-action@v1.x
        with:
            merge_method: squash
            time_zone: "Australia/Brisbane"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}